Make the contact fields of ContactInformation model unique coupled wi…
IMGIITRoorkee/omniport-backend-formula-one pull request #12
Opened 2020-09-22 07:09 UTC by ruddi10

Make contact fields of ContactInformation model unique coupled with their entity type

2020-09-22 07:45 UTC, dhruvkb requested changes

2020-09-22 07:45 UTC, dhruvkb commented on models/generics/contact_information.py
> +
Remove the blank line

2020-09-22 07:57 UTC, ruddi10 commented
Removed thanks for telling.

2020-09-22 08:26 UTC, pradumangoyal commented
I think the name passed in the `name` parameter should not have spaces in between. Better to replace those with underscores. You can rename the migration file semantically. Always check the PR title before opening a PR

2020-09-23 12:59 UTC, ruddi10 commented
Made the changes

2020-09-23 13:03 UTC, dhruvkb requested changes

2020-09-23 13:03 UTC, dhruvkb commented on models/generics/contact_information.py
> +     ]
Closing bracket not aligned with opening line.
```suggestion
        constraints=[
            models.UniqueConstraint(fields=['entity_content_type', 'primary_phone_number'], name='unique_primary_number'),
            models.UniqueConstraint(fields=['entity_content_type', 'secondary_phone_number'], name='unique_secondary_number'),
            models.UniqueConstraint(fields=['entity_content_type', 'email_address'], name='unique_email_address'),
            models.UniqueConstraint(fields=['entity_content_type', 'institute_webmail_address'], name='unique_institute_webmail_address'),
        ]
```

2020-09-23 13:04 UTC, dhruvkb commented on models/generics/contact_information.py
> +     ]
Also all these lines seem to be way over the 80 character limit.

2020-09-23 14:23 UTC, ruddi10 commented
Made the required changes

2020-09-23 14:39 UTC, dhruvkb requested changes

2020-09-23 14:39 UTC, dhruvkb commented on models/generics/contact_information.py
> +            'primary_phone_number'], name='unique_primary_number'),
This does look overly long but it's the convention followed across all models in the codebase.
```suggestion
            models.UniqueConstraint(
                fields=[
                    'entity_content_type', 
                    'primary_phone_number',
                ], 
                name='unique_primary_number',
            ),
```

2020-09-23 14:39 UTC, dhruvkb commented on models/generics/contact_information.py
> +            'primary_phone_number'], name='unique_primary_number'),
Note the trailing commas _everywhere_.

2020-09-26 10:04 UTC, dhruvkb approved these changes
I trust @pradumangoyal and @algomaster99 to look into the specifics. LGTM

2020-10-01 02:49 UTC, pradumangoyal approved these changes

2020-10-01 06:42 UTC, merged