Feature: Update upload_to file to accomodate new filemanager
IMGIITRoorkee/omniport-backend-formula-one pull request #14
Opened 2020-12-19 11:45 UTC by ayu023ban

2020-12-19 12:58 UTC, dhruvkb requested changes
Please see some older files from the repo to see the conventions and style guide we follow. It's unfortunate that you have to infer this from existing files instead of having an actual document, but maybe you can take it up.

2020-12-19 12:58 UTC, dhruvkb commented on utils/upload_to.py
> -
Why? Please keep newlines between imports of different kinds.

2020-12-19 12:58 UTC, dhruvkb commented on utils/upload_to.py
> +        """Return Updated file name in case of file already exists
See other comments to see how we style comments.

2020-12-19 12:58 UTC, dhruvkb commented on utils/upload_to.py
> +        """
Leave a newline after the comments.

2020-12-19 12:58 UTC, dhruvkb commented on utils/upload_to.py
> -
This is required, please do not remove.

2020-12-19 13:21 UTC, ayu023ban commented
@dhruvkb  i have made the required changes.
please look into the latest patch once again

2020-12-27 16:42 UTC, pradumangoyal commented
This custom `upload_to` should go in the respective app only.

2020-12-27 16:48 UTC, closed without merging